name: copyHtml

on:
  push:
    branches:
      - master

jobs:
  build_pdf:
    name: Copy html
    runs-on: ubuntu-latest

    steps:
      - name: Copy files to another repository
        uses: lubu12/copy-files-to-repository@v1
        # Recall that you have to create (now it's created) a secret called API_TOKEN_GITHUB with a token with repo permissions and then you have to add it to the repository secrets. See the repository of lubu12 for more information.
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # I want to copy file complete-summaries/index.html in th branch gh-pages of the repository victorballester7/victorballester7.github.io to the branch main of the repository victorballester7/complete-summaries
          source-files: complete-summaries/index.html assets
          destination-username: victorballester7
          destination-repository: complete-summaries
          destination-directory:
          destination-branch: main
          from-container: false
          commit-email: victor.ballester.ribo@gmail.com
          commit-message: "Update html and assets folder file"
