name: ReleasePDFfile

on:
  push:
    branches:
      - gh-pages

jobs:
  build_pdf:
    name: Copy html
    runs-on: ubuntu-latest

    steps:
      - name: Copy files to another repository
        uses: lubu12/copy-files-to-repository@v1
        # Recall that you have to create (now it's created) a secret called API_TOKEN_GITHUB with a token with repo permissions and then you have to add it to the repository secrets. See the repository of lubu12 for more information.
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: complete-summaries/index.html complete-summaries/assets/
          destination-username: victorballester7
          destination-repository: complete-summaries
          destination-directory:
          commit-email: victor.ballester.ribo@gmail.com
          commit-message: "Update html file"
